const productCardsData = [
  // --- Universal ---
  {
    name: "Gold Standard 100% Whey",
    brand: "Optimum Nutrition",
    img: "https://nutristore.co.uk/cdn/shop/files/optimum-nutrition-gold-standard-100-whey-protein-227kg-160485.png?v=1742901099",
    category: "Universal Weight-Gain Weight-Loss",
    price: 2850,
    inStock: true,
    flavour: ["Double Rich Chocolate", "Vanilla Ice Cream", "Strawberry"],
    macrosArr: [
      ["Protein", "24g"],
      ["Carbs", "3g"],
      ["Fat", "1g"],
    ],
  },
  {
    name: "ISO100 Hydrolyzed Whey Protein",
    brand: "Dymatize",
    img: "https://suppsrus.com.au/cdn/shop/files/Dymatize-Iso100-2.3kg-chocpb-elite-supps_99ca2443-1bdb-40e2-9886-9d171b6397ca.png?v=1749050465",
    category: "Universal Weight-Gain Weight-Loss",
    price: 3200,
    inStock: true,
    flavour: ["Fruity Pebbles", "Chocolate Peanut Butter", "Vanilla"],
    macrosArr: [
      ["Protein", "25g"],
      ["Carbs", "2g"],
      ["Fat", "0.5g"],
    ],
  },
  {
    name: "Greens Superfood Powder",
    brand: "Amazing Grass",
    img: "https://amazinggrass.com/cdn/shop/files/GreensBlend-og_grande.png?v=1747319554",
    category: "Universal",
    price: 1190,
    inStock: true,
    flavour: ["Berry", "Original", "Lemon Lime"],
    macrosArr: [
      ["Calories", "30"],
      ["Fiber", "2g"],
      ["Greens Blend", "7g"],
    ],
  },
  {
    name: "Ashwagandha KSM-66",
    brand: "MST",
    img: "https://mst-nutrition.de/cdn/shop/files/mstksm66ashwagandha70x15060kaps-1png.png?v=1739172895",
    category: "Universal Recovery",
    price: 540,
    inStock: true,
    flavour: ["Unflavored"],
    macrosArr: [
      ["Ashwagandha Extract", "600mg"],
      ["Withanolides", "5%"],
      ["Capsules", "60"],
    ],
  },
  {
    name: "Hydrolyzed Collagen Peptides",
    brand: "Vital Proteins",
    img: "https://i5.walmartimages.com/seo/Vital-Proteins-Collagen-Peptides-Beauty-Supplement-Powder-for-Hair-Skin-and-Nails-Unflavored-7-37-oz_b0daa5f3-d08a-4dcf-8cdb-1b132c4b3c2d.2f974e4ce159d5344274711c176f0e38.png",
    category: "Universal Recovery",
    price: 1480,
    inStock: true,
    flavour: ["Unflavored", "Vanilla", "Lemon"],
    macrosArr: [
      ["Collagen", "20g"],
      ["Vitamin C", "90mg"],
      ["Hyaluronic Acid", "80mg"],
    ],
  },
  // --- Strength ---
  {
    name: "Creatine Monohydrate",
    brand: "Optimum Nutrition",
    img: "https://assets.hyugalife.com/catalog/product/7/4/748927066623_1-photoroom.png-photoroom.png",
    category: "Strength Weight-Gain",
    price: 850,
    inStock: true,
    flavour: ["Unflavored"],
    macrosArr: null,
  },
  {
    name: "Test HD Booster",
    brand: "MuscleTech",
    img: "https://wee-prod-public.s3.eu-central-1.amazonaws.com/a4ff311c/73a78049/9b37e3bd/916e4b93/66b60b2da6fee4.07071355.medium.png",
    category: "Strength",
    price: 1100,
    inStock: false,
    flavour: null,
    macrosArr: null,
  },

  // --- Energy ---
  {
    name: "Psychotic Hellboy",
    brand: "Insane Labz",
    img: "https://cdn11.bigcommerce.com/s-qv3l6fwcff/images/stencil/1500x1500/products/6073/16142/psychoticblueraspberry__55086.1704736930.png?c=1",
    category: "Energy",
    price: 980,
    inStock: true,
    flavour: ["Blue-Raspberry", "Grape", "Lemonade"],
    macrosArr: [
      ["Caffeine", "90"],
      ["Beta-Ala", "40"],
      ["Creatine", "30"],
    ],
  },
  {
    name: "C4 Original Pre-Train",
    brand: "Cellucor",
    img: "https://images.hollandandbarrettimages.co.uk/productimages/HB/1500/065999_A.png",
    category: "Energy",
    price: 750,
    inStock: true,
    flavour: ["Unflavored", "Green-Apple"],
    macrosArr: [
      ["Caffeine", "150"],
      ["Beta-Ala", "25"],
      ["Creatine", "0"],
    ],
  },

  // --- Weight-Gain ---
  {
    name: "Rule 1 Mass Gainer",
    brand: "Rule 1",
    img: "https://blb.uz/image/cache/catalog/image/cache/catalog/tovar13/Mass_12lb_vanilla2-700x700.webp",
    category: "Weight-Gain",
    price: 1450,
    inStock: true,
    flavour: ["Vanila"],
    macrosArr: [
      ["Protein", "13"],
      ["Carbs", "82"],
      ["Fats", "5"],
    ],
  },
  {
    name: "Serious Mass Gainer",
    brand: "Optimum Nutrition",
    img: "https://www.bodyclub.gr/image/cache/catalog/Products/ON_Optimum_Nutrition/ON---Optimum-Nutrition-Serious-Mass-2730gr-Chocolate-Peanut-Butter-1200x1200.png",
    category: "Weight-Gain",
    price: 1690,
    inStock: false,
    flavour: ["Vanila", "Strawberry"],
    macrosArr: [
      ["Protein", "25"],
      ["Carbs", "110"],
      ["Fats", "4"],
    ],
  },

  // --- Weight-Loss ---
  {
    name: "Lipo-6 Black Ultra Concentrate",
    brand: "NutreX",
    img: "https://nutrex.com/cdn/shop/files/Lipo6-BlackUC-60.png?v=1740081437&width=350",
    category: "Weight-Loss",
    price: 720,
    inStock: true,
    flavour: null,
    macrosArr: null,
  },
  {
    name: "Hydroxycut Hardcore Elite",
    brand: "Muscletech",
    img: "https://www.muscletech.com/cdn/shop/files/mt-hydroxycut-hardcore-super-elite-120.png?v=1742823177",
    category: "Weight-Loss",
    price: 860,
    inStock: true,
    flavour: null,
    macrosArr: null,
  },

  // --- Recovery ---
  {
    name: "BCAA 2:1:1",
    brand: "Scivation Xtend",
    img: "https://teamflex.com.au/cdn/shop/products/Xtend_Original_90Serve_WatermelonExplosion.png?v=1625724630",
    category: "Recovery Universal",
    price: 880,
    inStock: true,
    flavour: ["Unflavored", "Blue-Raspberry", "Green-Apple", "Lemonade"],
    macrosArr: null,
  },
  {
    name: "Glutamine Micronized",
    brand: "Dymatize",
    img: "https://musclehousesupplements.com/wp-content/uploads/2021/09/Dymatize-Glutamine-front-pic-min-min-1-600x600.png",
    category: "Recovery Universal",
    price: 650,
    inStock: true,
    flavour: null,
    macrosArr: null,
  },

  // --- Vitamins ---
  {
    name: "Animal Pak Complex",
    brand: "Universal Nutrition",
    img: "https://gymbeam.ua/media/catalog/product/cache/70f742f66feec18cb83790f14444a3d1/a/n/animalpak44_front.png",
    category: "Vitamins Universal",
    price: 1150,
    inStock: true,
    flavour: null,
    macrosArr: null,
  },
  {
    name: "Opti-Men Complex",
    brand: "Optimum Nutrition",
    img: "https://content.optimumnutrition.com/i/on/on-opti-men_Image_01?$TTL_PRODUCT_IMAGES$&locale=en-us,en-gb,*",
    category: "Vitamins Universal",
    price: 780,
    inStock: true,
    flavour: null,
    macrosArr: null,
  },
];

export default productCardsData;
