const productCardsData = [
  {
    name: "Gold Standard Whey",
    brand: "Optimum Nutrition",
    img: "https://nutristore.co.uk/cdn/shop/files/optimum-nutrition-gold-standard-100-whey-protein-227kg-160485.png?v=1742901099",
    category: "Universal Weight-Gain Weight-Loss",
    price: 2850,
    inStock: true,
    flavour: ["chocolate", "vanilla", "strawberry"],
    macrosArr: [
      ["Protein", "24g"],
      ["Carbs", "3g"],
      ["Fat", "1g"],
    ],
    weight: "2270g",
  },
  {
    name: "ISO100 Whey Protein",
    brand: "Dymatize",
    img: "https://suppsrus.com.au/cdn/shop/files/Dymatize-Iso100-2.3kg-chocpb-elite-supps_99ca2443-1bdb-40e2-9886-9d171b6397ca.png?v=1749050465",
    category: "Universal Weight-Gain Weight-Loss",
    price: 3200,
    inStock: true,
    flavour: ["peanut-butter", "vanilla", "chocolate", "strawberry"],
    macrosArr: [
      ["Protein", "25g"],
      ["Carbs", "2g"],
      ["Fat", "0.5g"],
    ],
    weight: "2300g",
  },
  {
    name: "Whey Protein",
    brand: "MyProtein",
    img: "https://www.ssn.ug/wp-content/uploads/2021/02/myprotein-impact-whey-protein-1kg-p27187-17290_image-1.png",
    category: "Universal Weight-Gain Weight-Loss",
    price: 1950,
    inStock: true,
    flavour: ["chocolate", "caramel", "banana"],
    macrosArr: [
      ["Protein", "21g"],
      ["Carbs", "1.9g"],
      ["Fat", "1.9g"],
    ],
    weight: "1000g",
  },
  {
    name: "ISO Whey Zero",
    brand: "BioTechUSA",
    img: "https://belok.ua/image/cache/catalog/foto2019/Golds/loadkep.php-600x600.png",
    category: "Universal Weight-Gain Weight-Loss",
    price: 2650,
    inStock: true,
    flavour: ["cookies", "vanilla", "strawberry"],
    macrosArr: [
      ["Protein", "22g"],
      ["Carbs", "0.6g"],
      ["Fat", "0.5g"],
    ],
    weight: "2270g",
  },
  {
    name: "Delicious Whey Protein",
    brand: "QNT",
    img: "https://www.qntsport.com/1483-modal/delicious-whey-protein-908-g.jpg",
    category: "Universal Weight-Gain Weight-Loss",
    price: 2250,
    inStock: true,
    flavour: ["chocolate", "strawberry", "vanilla"],
    macrosArr: [
      ["Protein", "23g"],
      ["Carbs", "1.9g"],
      ["Fat", "1.5g"],
    ],
    weight: "908g",
  },
  {
    name: "100% Whey Protein",
    brand: "Scitec Nutrition",
    img: "https://scitec.cz/images/product_images/5146_6ad91ca8b447.webp",
    category: "Universal Weight-Gain Weight-Loss",
    price: 2480,
    inStock: true,
    flavour: ["vanilla", "strawberry", "chocolate"],
    macrosArr: [
      ["Protein", "22g"],
      ["Carbs", "1.4g"],
      ["Fat", "1.8g"],
    ],
    weight: "2350g",
  },
  {
    name: "Greens Superfood",
    brand: "Amazing Grass",
    img: "https://amazinggrass.com/cdn/shop/files/GreensBlend-og_grande.png?v=1747319554",
    category: "Universal",
    price: 1190,
    inStock: true,
    flavour: ["unflavored", "lemon"],
    macrosArr: [
      ["Calories", "30"],
      ["Fiber", "2g"],
      ["Greens Blend", "7g"],
    ],
    weight: "240g",
  },
  {
    name: "Ashwagandha KSM-66",
    brand: "MST",
    img: "https://mst-nutrition.de/cdn/shop/files/mstksm66ashwagandha70x15060kaps-1png.png?v=1739172895",
    category: "Universal Recovery",
    price: 540,
    inStock: true,
    flavour: ["unflavored"],
    macrosArr: [
      ["Ashwagandha Extract", "600mg"],
      ["Withanolides", "5%"],
      ["Capsules", "60"],
    ],
    weight: "60 caps",
  },
  {
    name: "Collagen Peptides",
    brand: "Vital Proteins",
    img: "https://i5.walmartimages.com/seo/Vital-Proteins-Collagen-Peptides-Beauty-Supplement-Powder-for-Hair-Skin-and-Nails-Unflavored-7-37-oz_b0daa5f3-d08a-4dcf-8cdb-1b132c4b3c2d.2f974e4ce159d5344274711c176f0e38.png",
    category: "Universal Recovery",
    price: 1480,
    inStock: true,
    flavour: ["unflavored", "vanilla", "lemon"],
    macrosArr: [
      ["Collagen", "20g"],
      ["Vitamin C", "90mg"],
      ["Hyaluronic Acid", "80mg"],
    ],
    weight: "209g",
  },
  {
    name: "Creatine Monohydrate",
    brand: "Optimum Nutrition",
    img: "https://assets.hyugalife.com/catalog/product/7/4/748927066623_1-photoroom.png-photoroom.png",
    category: "Strength Weight-Gain Universal",
    price: 850,
    inStock: true,
    flavour: ["unflavored"],
    macrosArr: null,
    weight: "300g",
  },
  {
    name: "Test HD Booster",
    brand: "MuscleTech",
    img: "https://wee-prod-public.s3.eu-central-1.amazonaws.com/a4ff311c/73a78049/9b37e3bd/916e4b93/66b60b2da6fee4.07071355.medium.png",
    category: "Strength",
    flavour: ["unflavored"],
    price: 1100,
    inStock: false,
    macrosArr: null,
    weight: "90 caps",
  },
  {
    name: "Psychotic Hellboy",
    brand: "Insane Labz",
    img: "https://cdn11.bigcommerce.com/s-qv3l6fwcff/images/stencil/1500x1500/products/6073/16142/psychoticblueraspberry__55086.1704736930.png?c=1",
    category: "Energy",
    price: 980,
    inStock: true,
    flavour: ["grape", "lemon"],
    macrosArr: [
      ["Caffeine", "90"],
      ["Beta-Ala", "40"],
      ["Creatine", "30"],
    ],
    weight: "210g",
  },
  {
    name: "C4 Shot",
    brand: "Cellucor",
    img: "https://gymbeam.ua/media/catalog/product/cache/bf5a31e851f50f3ed6850cbbf183db11/c/4/c4_pwo_60ml_shot_millions_strawberry.png",
    category: "Energy",
    price: 95,
    inStock: true,
    flavour: ["strawberry", "green-apple"],
    macrosArr: [
      ["Caffeine", "200"],
      ["Beta-Alanine", "1600"],
      ["Arginine", "500"],
    ],
    weight: "60ml",
  },
  {
    name: "Pre JYM High Stim",
    brand: "JYM Supplement Science",
    img: "https://rysesupps.com/cdn/shop/files/pbo_br_1.webp?v=1714077242",
    category: "Energy",
    price: 1580,
    inStock: true,
    flavour: ["grape", "lemon", "green-apple"],
    macrosArr: [
      ["Caffeine", "300"],
      ["Beta-Alanine", "2000"],
      ["Citrulline Malate", "6000"],
    ],
    weight: "420g",
  },
  {
    name: "N.O.-XPLODE Shot",
    brand: "BSN",
    img: "https://snwnutrition.com/cdn/shop/products/noxplode-rtd_0_1024x1024.png?v=1533428334",
    category: "Energy",
    price: 105,
    inStock: false,
    flavour: ["grape"],
    macrosArr: [
      ["Caffeine", "275"],
      ["Beta-Alanine", "1000"],
      ["Tyrosine", "250"],
    ],
    weight: "60ml",
  },
  {
    name: "C4 Original Pre-Train",
    brand: "Cellucor",
    img: "https://images.hollandandbarrettimages.co.uk/productimages/HB/1500/065999_A.png",
    category: "Energy",
    price: 750,
    inStock: true,
    flavour: ["unflavored"],
    macrosArr: [
      ["Caffeine", "150"],
      ["Beta-Ala", "25"],
      ["Creatine", "0"],
    ],
    weight: "195g",
  },
  {
    name: "Mass Gainer",
    brand: "Rule 1",
    img: "https://blb.uz/image/cache/catalog/image/cache/catalog/tovar13/Mass_12lb_vanilla2-700x700.webp",
    category: "Weight-Gain",
    price: 1450,
    inStock: true,
    flavour: ["vanilla"],
    macrosArr: [
      ["Protein", "13"],
      ["Carbs", "82"],
      ["Fats", "5"],
    ],
    weight: "2720g",
  },
  {
    name: "Mutant Mass Extreme 2500",
    brand: "Mutant",
    img: "https://proteinas.lt/7007-large_default/mutant-mass-xxxtreme-2500-3180g.jpg",
    category: "Weight-Gain",
    price: 1520,
    inStock: true,
    flavour: ["chocolate", "vanilla"],
    macrosArr: [
      ["Protein", "30"],
      ["Carbs", "255"],
      ["Fats", "9"],
    ],
    weight: "2270g",
  },
  {
    name: "Mass-Tech Extreme 2000",
    brand: "MuscleTech",
    img: "https://international.muscletech.com/wp-content/uploads/2022/01/muscletech-mass-tech-extreme-2000.png",
    category: "Weight-Gain",
    price: 1980,
    inStock: true,
    flavour: ["chocolate", "cookies"],
    macrosArr: [
      ["Protein", "60"],
      ["Carbs", "400"],
      ["Fats", "14"],
    ],
    weight: "4510g",
  },
  {
    name: "Serious Mass Gainer",
    brand: "Optimum Nutrition",
    img: "https://www.bodyclub.gr/image/cache/catalog/Products/ON_Optimum_Nutrition/ON---Optimum-Nutrition-Serious-Mass-2730gr-Chocolate-Peanut-Butter-1200x1200.png",
    category: "Weight-Gain",
    price: 1690,
    inStock: false,
    flavour: ["vanilla", "strawberry"],
    macrosArr: [
      ["Protein", "25"],
      ["Carbs", "110"],
      ["Fats", "4"],
    ],
    weight: "2730g",
  },
  {
    name: "Lipo-6 Black Ultra",
    brand: "NutreX",
    img: "https://nutrex.com/cdn/shop/files/Lipo6-BlackUC-60.png?v=1740081437&width=350",
    category: "Weight-Loss",
    price: 720,
    inStock: true,
    flavour: ["unflavored"],
    macrosArr: null,
    weight: "60 caps",
  },
  {
    name: "Animal Cuts Powder",
    brand: "Universal Nutrition",
    img: "https://www.sportsfuel.co.nz/cdn/shop/files/unnamed_4_cd7ed4dd-bcc2-4371-aff0-03d03ecb74bb.png?v=1736991035&width=1000",
    category: "Weight-Loss",
    price: 1150,
    inStock: true,
    flavour: ["unflavored"],
    macrosArr: [
      ["Caffeine", "250"],
      ["L-Carnitine", "1500"],
      ["Green Tea Extract", "200"],
    ],
    weight: "210g",
  },
  {
    name: "Shred JYM",
    brand: "JYM Supplement Science",
    img: "https://jymsupplementscience.com/cdn/shop/products/ss8-front.png?v=1635427518&width=1024",
    category: "Weight-Loss",
    price: 1340,
    inStock: true,
    flavour: ["unflavored"],
    macrosArr: [
      ["Acetyl-L-Carnitine", "1500"],
      ["Green Tea Extract", "500"],
      ["Caffeine", "200"],
    ],
    weight: "240 capsules",
  },
  {
    name: "Hydroxycut Hardcore",
    brand: "Muscletech",
    img: "https://www.muscletech.com/cdn/shop/files/mt-hydroxycut-hardcore-super-elite-120.png?v=1742823177",
    category: "Weight-Loss",
    price: 860,
    inStock: true,
    flavour: ["unflavored"],
    macrosArr: null,
    weight: "120 caps",
  },
  {
    name: "BCAA 2:1:1",
    brand: "Scivation Xtend",
    img: "https://teamflex.com.au/cdn/shop/products/Xtend_Original_90Serve_WatermelonExplosion.png?v=1625724630",
    category: "Recovery Universal",
    price: 880,
    inStock: true,
    flavour: ["unflavored", "green-apple", "lemon"],
    macrosArr: null,
    weight: "384g",
  },
  {
    name: "Glutamine Micronized",
    brand: "Dymatize",
    img: "https://musclehousesupplements.com/wp-content/uploads/2021/09/Dymatize-Glutamine-front-pic-min-min-1-600x600.png",
    category: "Recovery Universal",
    price: 650,
    inStock: true,
    flavour: ["unflavored"],
    macrosArr: null,
    weight: "300g",
  },
  {
    name: "Animal Pak Complex",
    brand: "Universal Nutrition",
    img: "https://gymbeam.ua/media/catalog/product/cache/70f742f66feec18cb83790f14444a3d1/a/n/animalpak44_front.png",
    category: "Vitamins Universal",
    price: 1150,
    inStock: true,
    flavour: ["unflavored"],
    macrosArr: null,
    weight: "44 packs",
  },
  {
    name: "Opti-Men Complex",
    brand: "Optimum Nutrition",
    img: "https://content.optimumnutrition.com/i/on/on-opti-men_Image_01?$TTL_PRODUCT_IMAGES$&locale=en-us,en-gb,*",
    category: "Vitamins Universal",
    price: 780,
    inStock: true,
    flavour: ["unflavored"],
    macrosArr: null,
    weight: "90 tabs",
  },
];

export default productCardsData;
